### ISSUE TITLE
I cannot import this terraform into IBM Cloud workspace.

### ISSUE THREAD

**Issue by fghoraishi** [terraform-ibm-modules/terraform-ibm-powervs-instance#67]
I get the following error when importing this terraform into IBM Cloud Schematic workspace.

Faad

 2023/07/27 16:16:35 Getting download command
 2023/07/27 16:16:39 [1m[31mFatal, could not download repo, Please check the provided repo url, provide token for private repos. Error: Failed to clone git repository, chown /tmp/test-workspace3542974631/tfws-3093674016/Brewfile: no such file or directory[39m[0m
 2023/07/27 16:16:39 [1m[31mProblems found with the Repository. Please Rectify and Retry[39m[0m
 2023/07/27 16:16:39 [1m[32mDone with the Activity[39m[0m

**Comment by surajsbharadwaj** [comment]
@fghoraishi do you still face an issue ?

**Comment by surajsbharadwaj** [comment]
NOt valid. There is no ibm_catalog.json file persent in this repo and this repo is not supported. Please fork and do it
